-- Eseguire una sola volta nel Supabase SQL Editor prima del deploy.
alter table public.orders add column if not exists customer_reference text;
alter table public.orders add column if not exists tracking_token text;
create unique index if not exists orders_tracking_token_unique on public.orders(tracking_token) where tracking_token is not null;

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  status text not null,
  created_at timestamptz not null default now()
);
create index if not exists order_status_history_order_id_idx on public.order_status_history(order_id,created_at);

create table if not exists public.client_tariffs (
  user_id uuid primary key,
  email text not null,
  tariff_mode text not null check (tariff_mode in ('storico','piena')),
  updated_at timestamptz not null default now()
);
create unique index if not exists client_tariffs_email_unique on public.client_tariffs(lower(email));

alter table public.order_status_history enable row level security;
alter table public.client_tariffs enable row level security;
-- Nessuna policy pubblica: l'accesso avviene solo tramite API server con service role.
